### ISSUE TITLE
Add configuration options for remote developement

### ISSUE THREAD

**Issue by l0ner** [sketchbuch/vsc-workspace-sidebar#11]
VSCode allows for WSL specific settings. This applies both to VSCode settinng and extension settings. Unfortunately currently it is not possible to have separate configuration for workspace sidebar. When trying to edit the WSL specific settings.json file, the workspaceSidebar options appear greyed out. In the GUI for settings under the remote WSL tab they are not present at all.

**Comment by sketchbuch** [comment]
I now have a more powerful laptop and can now use VSCode in a Windows VM. I shall be looking at this issue shortly

**Comment by sketchbuch** [comment]
Fixed in v2.0.0
