### ISSUE TITLE
Folder structure broken in v2.0.2

### ISSUE THREAD

**Issue by mhennessie** [sketchbuch/vsc-workspace-sidebar#150]
Currently running v2.02 and the folder structure is now broken. Some workspaces are in their folders but others are just in the root. I have all are saved in their site/client folder inside the ~/sites folder that I have this extension pointed to. If I install v1.7.1 it works as expected and how it has been.

**Comment by sketchbuch** [comment]
Can you please attach some screen shots, also what settings do you have for condense file tree. Also can you show the folder structure how it appears on the file system

**Comment by mhennessie** [comment]
Ok so this appears to be an issue with the Condense File Tree option. Unchecking that makes them appear like they do in v1.7.1.

**Comment by sketchbuch** [comment]
I'm not sure what issues it could be apart from maybe you didn't have it on before.
In tests I saw the same structure with 1.7.1 and 2.0.0. 

I have noticed some issues with condese and certain tree structures and explorer compact setting which I shall address in the next patch release.

Did you always have Condense File Tree enabled before?

**Comment by sketchbuch** [comment]
Closed as seems fixed
