### ISSUE TITLE
Extension is currently broken

### ISSUE THREAD

**Issue by rafaelgandi** [sketchbuch/vsc-workspace-sidebar#152]
Hi just noticed this yesterday, the extension seems to be broken and currently is unusable.
<img width="1237" alt="Screenshot 2024-03-20 at 5 37 51 AM" src="https://github.com/sketchbuch/vsc-workspace-sidebar/assets/1776362/988008ea-e722-41d8-be55-689c897ccdfe">

**Comment by sketchbuch** [comment]
Can you post your config for rootFolders here?

**Comment by sketchbuch** [comment]
Ah, it is the wrong structure. Early version of multirootfolders that I was working on had just an array of strings, but now they have a specific structure (minimum is path property).

See: https://github.com/sketchbuch/vsc-workspace-sidebar/blob/master/docs/Configuration.md#root-folders

**Comment by rafaelgandi** [comment]
Awesome! Its working now. Might be a good addition to have a helpful error message to nudge old version users to the new format.

Thanks man! 
Cheers
