### ISSUE TITLE
[Feature request] Display the explorer after opening a workspace in a new window

### ISSUE THREAD

**Issue by bgrand-ch** [sketchbuch/vsc-workspace-sidebar#173]
Hello,

I love your extension and use it every day at work.

Could you add an option to display the explorer after opening a workspace in a new window please?

Current steps:
1. Editing files in the explorer.
2. Need to change workspace.
3. Click on the "Workspaces" tab.
4. Select a workspace.
5. Open the workspace in a new window.
6. Return to the first workspace to continue working on it.
7. Click on the "Explorer" tab.

Desired steps:
1. Editing files in the explorer.
2. Need to change workspace.
3. Click on the "Workspaces" tab.
4. Select a workspace.
5. Open the workspace in a new window.
6. Auto-switch to "Explorer" tab.
7. Return to the first workspace to continue working on it.

**Comment by sketchbuch** [comment]
I can look into this and see if there is an API way to change the current view in the activity bar.

**Comment by sketchbuch** [comment]
Will be in v2.1.0
