### ISSUE TITLE
Shortcut to focus on search Workspace

### ISSUE THREAD

**Issue by davidperezgar** [sketchbuch/vsc-workspace-sidebar#21]
It should be nice not only have a shortcut for focus in the sidebar. One that focus on the search of the sidebar. That gives you one step less to open a WorkSpace...

Nice extension!

**Comment by sketchbuch** [comment]
Hi, You mean a keyboard shortcut? I'm looking into focusing the search, I did try but everything I tried did not work.

**Comment by sketchbuch** [comment]
Resolved in v1.2.7

- Inpurt is focused 
- Added keyboard shortcut to focus input
