### ISSUE TITLE
Root folder with trailing slash - first character is cut in paths

### ISSUE THREAD

**Issue by yrtimiD** [sketchbuch/vsc-workspace-sidebar#22]
If `Workspace Sidebar: Folder` setting has trailing slash - all shown paths have first character cut.
![image](https://user-images.githubusercontent.com/816805/118898294-e6f17380-b914-11eb-9bd0-c1ec556dd884.png)
![image](https://user-images.githubusercontent.com/816805/118898304-ec4ebe00-b914-11eb-8b75-21710cd7e34f.png)

**Comment by sketchbuch** [comment]
Fixed in v1.2.6
