### ISSUE TITLE
FR: show folders hierarchy

### ISSUE THREAD

**Issue by yrtimiD** [sketchbuch/vsc-workspace-sidebar#23]
In a big monorepo list of workspaces might be pretty long. It will be useful to allow switch between flat list and hierarchy view.

**Comment by sketchbuch** [comment]
I will think about this as it would require a lot of changes.

**Comment by sketchbuch** [comment]
I have started work on this issue and hope to have it in the next release

**Comment by sketchbuch** [comment]
Sorry, I hope to be finished with this issue soon as it holding up releasing the next version. The tree view has been started and I hope to finish soon

**Comment by sketchbuch** [comment]
I have a working version. I release a version soon to the marketplace. I started using @vscode/webview-ui-toolkit for various UI elements, but unfortunately it does not havea tree widget (there is a pr requesting this), so I needed to build the tree from scratch.

![Vsc](https://user-images.githubusercontent.com/16445037/159178869-a95a818a-ba40-4aee-a426-2e9db6746331.png)

**Comment by sketchbuch** [comment]
As you can see there are some spacing issues, wil try and fix those

**Comment by sketchbuch** [comment]
See v1.4.0 [Search depth has been increased 20 25 in v1.4.0](https://marketplace.visualstudio.com/items?itemName=sketchbuch.vsc-workspace-sidebar)
