### ISSUE TITLE
Add option to open a workspace in new window by default

### ISSUE THREAD

**Issue by anooprh** [sketchbuch/vsc-workspace-sidebar#27]
This is an enhancement/feature request but what would help me greatly is if on clicking a workspace, instead of opening it in the same window, it opens in a new window by default. 

I understand not everybody likes this option so it's best to have it as an option and disabled by default.

**Comment by sketchbuch** [comment]
Config option has been added and will be in the next release

**Comment by anooprh** [comment]
> Config option has been added and will be in the next release

Thank you 😃
