### ISSUE TITLE
Terminal processes are lost

### ISSUE THREAD

**Issue by TorsteinHonsi** [sketchbuch/vsc-workspace-sidebar#28]
When I switch workspaces, terminal processes are lost. 

Say in workspace A's terminal I run `tsc -b ts -w` to start a watch. Then switch to workspace B, then back to workspace A. Workspace A now presents a clean terminal to me, even though the watch process is still running rogue in the background.

**Comment by sketchbuch** [comment]
Hi, I shall look into this but I'm not sure there is anything I can do. I use the standard vscode commands to load workspaces and am not doing anything bespoke.

I found this issue: https://github.com/microsoft/vscode/issues/20013

Other people were asking for it, It seems like something is there to do this, but I#m not sure what exactly.

In the posts the author of the extension Terminals Manager mentions that his extension fixes the issue - I use this extension and it has the ability to persist terminals. It maybe the solution for your problem. I may not be able to provide one - this extension is about switching workspaces, not managing terminals but I shall look into it some more.

**Comment by sketchbuch** [comment]
Closed due to inactivity
