### ISSUE TITLE
Increase maximum for searchdepth

### ISSUE THREAD

**Issue by LaserKaspar** [sketchbuch/vsc-workspace-sidebar#40]
![image](https://user-images.githubusercontent.com/30759364/148620882-e230e08b-8614-4cee-8f2b-83b2e9f09b17.png)
For some reason, the search depth is limited to 5.
It would be great if it could be changed to "0 - infinity"
0 or -1 for no limit
any other int for a maximum of that int

**Comment by LaserKaspar** [comment]
Great! Looking forward to the next release (:

**Comment by sketchbuch** [comment]
Hi. I will add this to the next version for the up coming week. The big blocker is now done. See: https://github.com/sketchbuch/vsc-workspace-sidebar/issues/23

So I can talk small issues now like depth, but I will set a maximum. I don't want it looking for ever. I will also need to see how the file tree view works with a deeper folder structure

**Comment by sketchbuch** [comment]
I will also merge your german translations

**Comment by sketchbuch** [comment]
Can you maybe make 2 PRs? One for translations and one for the depth changes? I left some comments on your PR

**Comment by sketchbuch** [comment]
Search depth has been increased 20 25 in v1.4.0

**Comment by LaserKaspar** [comment]
Thanks, 25 is enough for now, so I closed my first PR (:
I'll make a new PR for the german translation only 👍
Also, the new tree-view is gorgeous! Keep it up!

**Comment by sketchbuch** [comment]
@LaserKaspar i haven't tested thd tree with a really deep folder system, I think changes will be needed to accomdate a really deep tree. I shall start on this, this week
