### ISSUE TITLE
Show/Parse actual workspace file names, without removing CAPITAL letters and punctuation (e.g. hyphen, underscore)

### ISSUE THREAD

**Issue by carloscadux** [sketchbuch/vsc-workspace-sidebar#42]
Could you please consider showing/parsing the actual workspace file names, without removing CAPITAL letters and punctuation (e.g. hyphen, underscore)?
Thank you!

![image](https://user-images.githubusercontent.com/7339389/157255083-13687574-86b8-423a-a250-40fe9c29050d.png)

**Comment by sketchbuch** [comment]
I plan on releasing a new version this coming week and will add a config option for this. I was blocked by https://github.com/sketchbuch/vsc-workspace-sidebar/issues/23 and couldn't address this sooner

**Comment by carloscadux** [comment]
Great news! Thanks for the feedback 👍

**Comment by sketchbuch** [comment]
See v1.4.0 [Search depth has been increased 20 25 in v1.4.0](https://marketplace.visualstudio.com/items?itemName=sketchbuch.vsc-workspace-sidebar)
