### ISSUE TITLE
v1.4.0: When 'Show Folder Hierarchy' is checked the workspaces are disappearing. When 'flat' they are listed.

### ISSUE THREAD

**Issue by carloscadux** [sketchbuch/vsc-workspace-sidebar#47]
Hi.
As shown in the screen-recording below, when 'Show Folder Hierarchy' is checked the workspaces are disappearing. 
When unchecked, the 'flat' list is shown properly. 
What can be going wrong?
Thanks

![vsc-workspace-sidebar](https://user-images.githubusercontent.com/7339389/159324092-23e14ba8-7c91-47e9-9f80-b639d22a34c0.gif)

**Comment by sketchbuch** [comment]
Can you turn on dev tools from the help menu and see if anything appears there

**Comment by sketchbuch** [comment]
Ok... that is the issue. The workspaces show up in list view but not in tree if there are no subfolders. I shall work on a fix for this.

**Comment by sketchbuch** [comment]
Fixed in v1.4.1
