### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by ehagerty** [sketchbuch/vsc-workspace-sidebar#55]
Not sure where else to put this - thank you so much for taking the time to build this extension.  It so perfectly fits my use case and has made my workflow immensely more efficient.  If you use something like https://www.buymeacoffee.com/ for donations let me know as I'm happy to make one for the benefit it has provided.

**Comment by sketchbuch** [comment]
You are welcome, currently I don't have any way to donate but I will consider looking into how this could be done for the future. ;)

**Comment by ehagerty** [comment]
This is a popular one if it is of any use to you. https://www.buymeacoffee.com

**Comment by jtanguy** [comment]
Thank you for this extension indeed. It does one job, and one job well, and I use it daily
