### ISSUE TITLE
Condense option enhancement: remove intermediate folders with only one folder inside

### ISSUE THREAD

**Issue by jtanguy** [sketchbuch/vsc-workspace-sidebar#57]
I was wondering if it would be possible to further condense the workspace tree by removing intermediate folders that contain only one folder.
In my daily use of this extension, I have separate main folders for each context: personal, company, and client-related. Inside those folders I have my cloned repos. To avoid cluttering those main folders, I usually have a `.vscode` folder where I put my workspaces to keep the main folder self-contained.

```
Perso
├── .vscode
│   ├── microservices.code-workspace
│   ├── reblog.code-workspace
│   └── wordle.code-workspace
├── opentelemetry (git repo)
├── reblog (git repo)
└── wordle (git repo)
```

The condensed view does remove the `.vscode` folder when there is only one workspace inside, and I would like to condense it by either removing it, or do what github does, which is append it to its parent, i.e. `Perso / .vscode` 

![image](https://user-images.githubusercontent.com/551107/175281142-d9194dd7-3de9-4b7e-85a0-717b25084a42.png)

I can work on this feature if you want

**Comment by sketchbuch** [comment]
I was actually going to mofify the folder tree in the same way the file explorer compresses folders: "folder a/ folder b / folder c" but haven't got round to doing it.

**Comment by jtanguy** [comment]
Either way does the job fine.
On one hand, removing the unnecessary folders makes the output cleaner and more concise, on the other hand, collapsing like in the explorer view properly displays all the complexity.

I would lean more on the "reuse the explorer methods" to be consistent with the rest of the UI

**Comment by jtanguy** [comment]
I just re-read your question (and finally understood it). Ideally I'd think using the explorer option with a possible override for this plugin, but the override part may not be used at all.

Le'ts use the global explorer config

**Comment by sketchbuch** [comment]
You can [download](https://drive.google.com/file/d/1lvTIMcyFz5bUisqRe7AqLo1kMzqpQ9Kf/view?usp=sharing) this version and try it.

**Comment by sketchbuch** [comment]
<img width="1000" alt="Bildschirmfoto 2022-06-24 um 17 19 15" src="https://user-images.githubusercontent.com/16445037/175569137-fb11091c-cb03-45a6-8022-2221f9d66759.png">

**Comment by jtanguy** [comment]
It works great ! Thanks 

![image](https://user-images.githubusercontent.com/551107/176126182-7056629b-756f-471d-82ac-6daaba32e055.png)

**Comment by sketchbuch** [comment]
OK. I shall make a new release at the weekend so that you can use the market place version again

**Comment by jtanguy** [comment]
I noticed you kept the old compacting behavior too.
I just created a new workspace in a different folder, and the .vscode folder is missing. If I add another workspace it reappears.

![image](https://user-images.githubusercontent.com/551107/176187614-edf76373-6faf-4581-8682-9e5f7f9f4047.png)

**Comment by sketchbuch** [comment]
Yes, the old condense I left in as they are two different behaviours. 

Not everyone will want condense, and compact uses the explorer setting and all it does is display empty folders together with slashes in between.

**Comment by sketchbuch** [comment]
In v1.4.2
