### ISSUE TITLE
New feature: auto-close the sidebar on workspace switch

### ISSUE THREAD

**Issue by jtanguy** [sketchbuch/vsc-workspace-sidebar#58]
I have a small feature request, and I'd like to run it by you first before attempting to code it.

Could it be possible to add a config option to auto-close the sidebar after a workspace change ? 
Closing the sidebar is often the first action I do after switching workspaces.

This would happen in the current window if the workspace is opened in the current window, or both windows if the workspace is opened on a new window.

**Comment by sketchbuch** [comment]
How do you mean close the sidebar? You mean the workspace sidebar? This already happens as the explorer view is selected automatically. Or do you mean the whole activity panel sidebar (everything on the left)? There is a command for this (Toogle Primary Side Bar) - same as used by the icon in the top right of the window

<img width="311" alt="Bildschirmfoto 2022-06-23 um 15 46 28" src="https://user-images.githubusercontent.com/16445037/175314563-205d3a43-8048-4d27-aaa6-80aee9c2798a.png">
.

**Comment by sketchbuch** [comment]
"Toogle Primary Side Bar" affects only the current window. I'm not sure without looking at the API if you can close all sidebars in all windows, but there is a way to get all windows so maybe they could be iterated over.

**Comment by sketchbuch** [comment]
Feel free to fork and make a pr as I don't have time for this at the moment. If you need any help let me know.

**Comment by jtanguy** [comment]
Thanks for the insight. I was not sure about how to do it; it's my first time working on a vscode plugin.
I'll try to do it myself
