### ISSUE TITLE
Display relative/full path of workspaces in Workspace Sidebar

### ISSUE THREAD

**Issue by andrsmllr** [sketchbuch/vsc-workspace-sidebar#6]
When searching from a home folder down through subfolders, multiple workspaces with the same name may exist.
This results in multiple workspaces with the same name in the Workspaces Sidebar. The only way to distinguish between them is to open the workspace and check what's inside.
It would be nice if the relative path from the home folder to the workspaces could be displayed, alternatively to showing just the workspace name. This would improve usability a lot when working with multiple tags/branches which each contain a workspace of the same name.

**Comment by sketchbuch** [comment]
Added in v1.1.7
See: https://github.com/sketchbuch/vsc-workspace-sidebar/pull/7

**Comment by sketchbuch** [comment]
I may optimise this in the next release to remove the folder path from the path displayed ("~/Dev" in the above screenshot). For now though this is hopefully sufficient.
