### ISSUE TITLE
Workspace list is empty

### ISSUE THREAD

**Issue by mhennessie** [sketchbuch/vsc-workspace-sidebar#62]
I just started setting this up and it finds workspaces, says "WORKSPACES: 2" at the top, but then does not show any workspaces listed below. I am getting a console error when I switch to the Workspaces Sidebar item (see screenshot), might not be related.

<img width="551" alt="Screen Shot 2022-08-25 at 10 53 15 AM" src="https://user-images.githubusercontent.com/8999894/186698921-cd4d2944-d22c-47bb-93f6-a2792419185b.png">

**Comment by mhennessie** [comment]
Never mind, my workspace has the same name as the folder and it is stripping out the name and then showing nothing.

**Comment by sketchbuch** [comment]
So you have a workspace file like this?

"/.../projects/flutter_test/flutter_test.code-workspace"

If this is causing errors, I can look into that, but as a short term fix, renaming would probably be best.

**Comment by mhennessie** [comment]
Essentially... it is like this:

"/sites/client/domain.com.code-workspace/"
"/sites/client/domain.com"

I'd like to have the Workspace Sidebar list them as domain.com so I could have them in the file tree as 

Client
- domain.com
- xyz.com
- foo.com

**Comment by mhennessie** [comment]
it is any punctuation in the name of the workspace that causes this.

**Comment by mylesduncanking** [comment]
I am having the same issue, i name my workspaces domain.com.code-workspace and none are displaying in the list however the count at the top is correct

**Comment by sketchbuch** [comment]
Ok, I have some time to look into this issue and hope to release a fix soon. Thanks both of you for reporting it.

**Comment by sketchbuch** [comment]
I have fixed the issue and will be releasing a fix soon

**Comment by sketchbuch** [comment]
In v1.4.2
