### ISSUE TITLE
Configurable sidebar icon depending on workspace

### ISSUE THREAD

**Issue by bilogic** [sketchbuch/vsc-workspace-sidebar#66]
![image](https://user-images.githubusercontent.com/946010/218273190-82a6a508-67b8-47e9-afae-ef10f1cefa4d.png)

Would you be able to display a different sidebar icon (configured in settings) depending on the workspace that is opened? This will greatly help me identify which workspace I'm in. An image badge will work too, but a favicon would be best.

I actually requested for something similiar here https://github.com/microsoft/vscode/issues/174153

**Comment by sketchbuch** [comment]
I need to look into if this is even possible.

**Comment by bilogic** [comment]
<img width="495" alt="image" src="https://github.com/sketchbuch/vsc-workspace-sidebar/assets/946010/1d38d7f0-156f-4813-8a85-6aa417caf10a">

Thanks, just wanted to show why I'm lost on which project I'm on. Even 2 alphabets in a badge will help. :)

**Comment by sketchbuch** [comment]
I have looked into this further and can't do this.

1. The icon is defined in a static json file (package.json) so I can't change it.
2. There is a badge for web views but they [are not activated and displayed until the user clicks on the extension icon](https://github.com/microsoft/vscode/issues/146330) in the activity bar. Before then, there is no way to calculate anything to display
3. The badge API only supports setting numbers in the badge, not text.

Sorry, but given the current state of the API I can't do this. An alternative would be the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension.

**Comment by bilogic** [comment]
@sketchbuch thanks!!
