### ISSUE TITLE
Increase settings scope

### ISSUE THREAD

**Issue by bilogic** [sketchbuch/vsc-workspace-sidebar#67]
I'm using code server and it allows for 4 levels of settings

1. User
2. Remote
3. Workspace
4. Folder

I tried move the settings to `Remote` but get the following error:

![image](https://user-images.githubusercontent.com/946010/218274500-e9a7d14c-3e6f-4b26-bf90-415c8db54620.png)

Thank you.

**Comment by sketchbuch** [comment]
Fixed in v2.0.0
