### ISSUE TITLE
Configurable icon for each workspace on list

### ISSUE THREAD

**Issue by szczemp** [sketchbuch/vsc-workspace-sidebar#69]
I have tons of projects (workspaces). Mostly php, python, golang. Many of them have similar names in different languages. For example, I have two projects with similar names customProject-php and customProject-py. The only difference is php and py at the end of the name. It would be great if I could set icons for projects.

**Comment by sketchbuch** [comment]
I'm not sure I want to build in some kind fo system for assigning icons to workspaces. I'd like to find a solution that does it automatically if an option to show icons is enabled.

I will look into using some kind of prefix/suffix/parent folder name string check to see if an icon can be some how matched.

**Comment by sketchbuch** [comment]
I have looked into this further and can't do this.

1. The icon is defined in a static json file (package.json) so I can't change it.
2. There is a badge for web views but they [are not activated and displayed until the user click on the extension icon](https://github.com/microsoft/vscode/issues/146330) in the activity bar. Before then, there is no way to calculate anything to display
3. The badge API only supports setting numbers in the badge, not text.

Sorry, but given the current state of the API I can't do this. An alternative would be the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension.

**Comment by sketchbuch** [comment]
Sorry wrong issue

**Comment by sketchbuch** [comment]
Nearly done

![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/16445037/32f361f7-3b89-4a82-8469-82e573307a4c)

**Comment by sketchbuch** [comment]
Done. Will be in v1.6.0

**Comment by sketchbuch** [comment]
Please read the [documentation](https://github.com/sketchbuch/vsc-workspace-sidebar/blob/master/docs/File%20Icon%20Themes.md) on how to configure the matching of icons to workspaces.
