### ISSUE TITLE
Caching of workspaces.

### ISSUE THREAD

**Issue by LaserKaspar** [sketchbuch/vsc-workspace-sidebar#87]
Is it possible to cache all workspaces previously found in order to speed up the initial draw?

Also it seems like there is no way to exclude certain folder names (e.g. .git, node_modules, etc...). Is this true?

**Comment by sketchbuch** [comment]
It is cached, for 12 hours.

If you would help I could provide a config for that to let you specify a config duration

**Comment by sketchbuch** [comment]
Node modules is excluded, as well as other folders to speed up collecting workspaces. Possibly that could be exposed as a config option too.
See: https://github.com/sketchbuch/vsc-workspace-sidebar/blob/master/src/utils/fs/collectFilesFromFolder.ts
(foldersToIgnore)

**Comment by LaserKaspar** [comment]
Sure, how could I help? 
Not dumping caches, or only dumping caches after a refresh is completed would be great. Because waiting for a refresh takes time and if you didn't change anything and just want to open something quickly is isn't necessary to block user input. 
Exposing foldersToIgnore would also be great.
I just quickly made a script that copies all of my workspaces in a seperate folder & modifying them to still point at the same folders and that sped up everything massively.

**Comment by sketchbuch** [comment]
I will put this stuf into the next version.

**Comment by sketchbuch** [comment]
Will be in version 1.7.0

**Comment by sketchbuch** [comment]
Should be out now

**Comment by LaserKaspar** [comment]
Working great now! Thanks a lot!
